[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.33"
log = "0.4.22"
num-derive = "0.4.2"
num-traits = "0.2.19"
serde = { version = "1.0.210", features = ["derive"] }
